### ISSUE TITLE
Support agent-groups and agents endpoints

### ISSUE THREAD

**Issue by paragbaxi** [tenable/Tenable.io-SDK-for-Python#11]
Critical for programmatic deployment and management of Tenable.io agents.

The {scanner_id} value must always be 1.

Example:
GET /scanners/1/agent-groups HTTP/1.1
Host: cloud.tenable.com
X-Cookie: token=REDACTED_DONT_EVEN_TRY
Cache-Control: no-cache

Note the "1" after "/scanners/". That's what is hardcoded. "0" doesn't work. "2" doesn't work. "1" does.

**Comment by veedam** [comment]
Submitted pull request for agent and agent-groups endpoints. Please review.

**Comment by alanfung** [comment]
Thanks @veedam , we already have completed this work and will be merging it shortly. Thank you for your contribution.

**Comment by alanfung** [comment]
@veedam thank you for your contribution, we've actually completed this work already and it's not merged.

**Comment by alanfung** [comment]
Resolved by:

3c417f6a
e63ca165
