### ISSUE TITLE
web-app support

### ISSUE THREAD

**Issue by grumpywocoffee** [tenable/Tenable.io-SDK-for-Python#110]
Hi,

Could support for the was-scan be added to the project?

These are now available at the cloud api site https://cloud.tenable.com/api#/resources/was-scans.

Thanks,

Stephen Cannons

**Comment by tenableAndrew** [comment]
Generally all WAS functionality should be covered by the existing asset/editor/scan/etc APIs that already exist. The documentation lists these separately, but they use the same underlying endpoints, sometimes with additional parameters. 

I'm going to close this now, but please feel free to re-open if you find any missing WAS functionality.
