### ISSUE TITLE
asset_lists (target_groups) still used in request payload, add support in ScanSettings

### ISSUE THREAD

**Issue by p-rs** [tenable/Tenable.io-SDK-for-Python#113]
https://github.com/tenable/Tenable.io-SDK-for-Python/blob/f571d6945dc0ba2c518e5345590727dd37774930/tenable_io/api/models.py#L1648-L1682

Right now I'm working around this issue by extending the ScanSettings class by adding this to the init:
`asset_lists=[]`
and this:
`self.asset_lists = asset_lists`
to be able to assign target_groups to Scans.

Thank you!

**Comment by tenableAndrew** [comment]
This was addressed in [Release v1.6.0](https://github.com/tenable/Tenable.io-SDK-for-Python/releases/tag/v1.6.0)
