### ISSUE TITLE
How to create a new scan 

### ISSUE THREAD

**Issue by karthiknannapaneni** [tenable/Tenable.io-SDK-for-Python#115]
There are only 3 fields available is SDK now. but the actual scan needs more inputs like schedule, description etc...
scan = client.scan_helper.create(
        name=scan_name,
        text_targets=test_targets,
        template='basic'
    )

{
    "uuid": {template_uuid},
    "settings": {
        "name": {string},
        "description": {string},
        "emails": {string},
        "enabled": {boolean},
        "launch": {string},
        "folder_id": {integer},
        "policy_id": {integer},
        "scanner_id": {integer},
        "text_targets": {string}
    }
}

**Comment by tenableAndrew** [comment]
For more advanced configuration options you can use the [ScansApi.create](https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/api/scans.py#L23) method which takes a `CreateScanRequest` as an argument.

Here's an example creating a Basic Network scan of a single target using a cloud scanner as the scanner.
```
from tenable_io.client import TenableIOClient
from tenable_io.api.scans import ScanCreateRequest
from tenable_io.api.models import ScanSettings

client = TenableIOClient()

scanners = {scanner.name: scanner.id for scanner in client.scanners_api.list().scanners}
template = client.scan_helper.template(name='basic')

scan_id = client.scans_api.create(
    ScanCreateRequest(
        template.uuid,
        ScanSettings(
            'My Scan',
            'target1.mycompany.com',
            scanner_id=scanners['US Cloud Scanner']
        )
    )
)
```

**Comment by karthiknannapaneni** [comment]
Thank you

**Comment by rukender** [comment]
How can I add a template of the Advance scan? currently, the above script will run the basic scan. I want to run advance scan or how can i use my own scan template?
