### ISSUE TITLE
Example for running credentialed scan using Python SDK

### ISSUE THREAD

**Issue by s-ritik16n** [tenable/Tenable.io-SDK-for-Python#120]
I'm using Python SDK to run scans on tenable.io but I can't find any snippet which explains initiating the scans with credentials. It would be great to have an example for that.

**Comment by tenableAndrew** [comment]
Hi @s-ritik16n , sorry for the delay on this. I hope to have the Managed Credentials API added by the end of this week. I'll ensure that along with this we include an example of how to configure a scan with managed credentials. 

Thanks for your patience.

**Comment by tenableAndrew** [comment]
This was address in #138
