### ISSUE TITLE
*Fixed* "ImportError: No module named tenable_io.client" for Python

### ISSUE THREAD

**Issue by Pernapple** [tenable/Tenable.io-SDK-for-Python#121]
SDK was working last week but now when I try to run my script it doesnt even get past line 1. I get this error that the module isn't found. Tried using Python v 2.7.15 and 3.7.4 and neither one works. Tried uninstalling and reinstalling the SDK too, still no luck.

First 6 lines look like this:

from tenable_io.client import TenableIOClient
from tenable_io.api.scans import ScanLaunchRequest
from tenable_io.api.models import ScanSettings
import datetime
import configparser
import io
import os

**Comment by Pernapple** [comment]
Python 2.7.15 and 3.7.4 didn't allow me to import the modules, but v3.7.3 worked perfectly.

**Comment by SteveMcGrath** [comment]
Likely that the module was only installed in your 3.7.3 site-packages.
