### ISSUE TITLE
How to add the agent group(s) in Advanced Agent Scan? 

### ISSUE THREAD

**Issue by aidanadia** [tenable/Tenable.io-SDK-for-Python#122]
Hi, I have a question. I am creating a new Advanced Agent Scan scan using [ScansApi.create](https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/api/scans.py) method and I want to specify the agent group in the scan. But in the ScanSettings model : 

> self.name = name
        self.description = description
        self.emails = emails
        self.enabled = enabled
        self.launch = launch
        self.starttime = starttime
        self.rrules = rrules
        self.timezone = timezone
        self.file_targets = file_targets
        self.launch_now = launch_now
        self.folder_id = folder_id
        self.policy_id = policy_id
        self.scanner_id = scanner_id
        self.text_targets = text_targets
        self.acls = acls
        self.asset_lists = asset_lists

there is no agent group attribute to add. Is there any way that I can create an agent scan and add the agent group to the scan using the Tenable API? 

Thank you!

**Comment by tenableAndrew** [comment]
Hi @aidanadia this should be fixed in v1.10.0

**Comment by aidanadia** [comment]
> Hi @aidanadia this should be fixed in v1.10.0

Thanks @tenableAndrew !
