### ISSUE TITLE
Add examples for user management

### ISSUE THREAD

**Issue by Brueggus** [tenable/Tenable.io-SDK-for-Python#126]
Hi,
could you add some examples for adding/editing/deleting users in tenable.io?

Thanks!

**Comment by tenableAndrew** [comment]
Hi @Brueggus,

I'll add a new examples file for user management and check to see whether our documentation could be made more clear. 

Thanks

**Comment by tenableAndrew** [comment]
This has been added in https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/examples/users.py
