### ISSUE TITLE
Tenable SDK Web App Scan PDF Download Issue

### ISSUE THREAD

**Issue by rara092** [tenable/Tenable.io-SDK-for-Python#130]
I am trying to use the Tenable SDK to launch a scan and download the report in the pdf format. I took the code straight from the Tenable website. The scan is launched properly but the problem is with the SDK's download functionality. The exact problem is the pdf that is downloaded doesn't have any data. I have attached the PDF to this message. I am referring to the following link: https://developer.tenable.com/docs/tips-on-using-the-tenable-python-sdk-how-to-run-internal-scans-scan-imports-and-exports-and-more 
[testScanGoogle.pdf](https://github.com/tenable/Tenable.io-SDK-for-Python/files/3779333/testScanGoogle.pdf)

My code:

from tenable_io.client import TenableIOClient
client = TenableIOClient(access_key='{YOUR ACCESS KEY}', secret_key='{YOUR SECRET KEY}')
scan = client.scan_helper.create(name='testScanGoogle', text_targets='http://google.com', template='Web App Scan')
scan.launch().download('testScanGoogle.pdf', scan.histories()[0].history_id)

**Comment by tenableAndrew** [comment]
Hi @rara092, We should hopefully have a fix up for this later today in the next release. 

See https://github.com/tenable/Tenable.io-SDK-for-Python/pull/129

There are slight differences between exports for Web App Scans and non-Web App Scans, even though they use the same endpoints.

**Comment by rara092** [comment]
That would be perfect. Thanks

**Comment by tenableAndrew** [comment]
The fix should be available in https://github.com/tenable/Tenable.io-SDK-for-Python/releases/tag/v1.9.1

You'll need to include a named argument, `is_was=True` to the scan helper download method.
ex.
```
from tenable_io.client import TenableIOClient

client = TenableIOClient()
scan = client.scan_helper.create(name='MY TEST SCAN', text_targets='http://my.atrget.com', template='was_overview')
scan.launch().download('MY_TEST_SCAN.pdf', scan.histories()[0].history_id, is_was=True)
```

**Comment by rara092** [comment]
Thanks for the update. I tried out the v1.9.1 and it works as expected. Once again, thanks for the quick turnaround.
