### ISSUE TITLE
Error with object 'ScanDetails' and 'id' attribute

### ISSUE THREAD

**Issue by valoulou** [tenable/Tenable.io-SDK-for-Python#136]
Hello,

It seems that following the latest updates several problems have appeared.

- There is a print in the ```tenable_io>api>scan.py``` file line 71.

- When you use the `scan_helper.id(1234)` function the program will call `scan_api.details(1234)` who will return a ScanDetails object. On line 57 of the file `tenable_io>helpers>scan.py` it looks as if the 'id' attribute of the ScanDetails object is requested. When we look in the `models.py` file it seems that this object does not have this attribute.

Is it an error or a misunderstanding?

I'm using Python 2.7.

Thank you ! =)

**Comment by tenableAndrew** [comment]
Good catch on both points, I'll have a fix up shortly.

**Comment by valoulou** [comment]
Thanks @tenableAndrew 👍

**Comment by cberg2048** [comment]
I am also seeing this and it's blocking some work. Great Find @valoulou !!

**Comment by valoulou** [comment]
Thanks @cberg2048 👍

**Comment by tenableAndrew** [comment]
@valoulou let me know if the latest release (v1.10.1) works out better for you.

**Comment by valoulou** [comment]
@tenableAndrew Yes it works for me ! 👍 🎉 

Thanks again
