### ISSUE TITLE
ERROR:tenable_io:'CaseInsensitiveDict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by tenableAndrew** [tenable/Tenable.io-SDK-for-Python#19]
I'm seeing this error frequently when using the SDK coming from the requests library, it doesn't _seem_ to be doing anything bad, but it would be nice to smother these errors if they aren't causing problems.

**Comment by tenableAndrew** [comment]
This is potentially due to python 3.5.1. The Error does not occur when using 2.7.10. I will continue to investigate.

**Comment by alanfung** [comment]
Are you able to reproduce this with consistency? If so, can you share your script?

**Comment by tenableAndrew** [comment]
When using python 3.5.1, with logging set to any level lower than CRITICAL, it seems like this is happening.

ex. 
```
from tenable_io.client import TenableIOClient
client = TenableIOClient()
client.server_api.status()
```
Will result in ```ERROR:tenable_io:'CaseInsensitiveDict' object has no attribute 'iteritems'```
However, it is not preventing the request, it just seems to be noise. 

I believe this means that somewhere is calling <dict>.iteritems(), which was changed to <dict>.items() in Python 3, which is why the error only appears when python3 is used. I know libraries like future.utils or six have version agnostic iteritems functions. I'm looking around to see if this is being throw somewhere within the SDK or within another library.

**Comment by alanfung** [comment]
@tenableAndrew this should be fixed here now: https://github.com/tenable/Tenable.io-SDK-for-Python/commit/cab361e090b09cc206b3fb68519eef0e47ee9f19#diff-4477ce2a88f9b2189a6905c25ce2f026

Please reopen this if you believe otherwise, thanks!
