### ISSUE TITLE
Update FileApi.upload() to be more user-friendly

### ISSUE THREAD

**Issue by tenableAndrew** [tenable/Tenable.io-SDK-for-Python#23]
We should update this function to work similarly to how the ScanHelper.import_scan() function is used so that the user can just pass in the path of the file they'd like to upload. 

ex.
```
def upload(self, file):
        """Upload a file

        :param file: Path of file to upload.
        :raise TenableIOApiException:  When API error is encountered.
        :return: The name of the uploaded file.
        """
        if not os.path.isfile(file):
            raise TenableIOException(u'File does not exist at path.')

        with open(file, 'rb') as ufile:
            response = self._client.post('file/upload', files={'Filedata': (os.path.basename(ufile.name), ufile)})
            return loads(response.text).get('fileuploaded')
```

**Comment by alanfung** [comment]
We are keeping all the API wrappers as thin as possible, staying true to the API. Any additional UX enhancements are done in the helper. Is there any workflow where a user would use the `FileApi.upload` directly?

**Comment by tenableAndrew** [comment]
I believe other file imports, such as target-group and exclusions both use the POST /file/upload endpoint as a means of importing csv files.
