### ISSUE TITLE
ScansAPI Details Filter Parameters

### ISSUE THREAD

**Issue by thathaneydude** [tenable/Tenable.io-SDK-for-Python#47]
Currently unable to provide a filter when requesting the details for a scan. Please allow for a filter to be passed and appended to the get parameters when retrieving a scan's details via the ScansAPI details def.

**Comment by alanfung** [comment]
@thathaneydude are you referring to the wrapper for this call? https://cloud.tenable.com/api#/resources/scans/details

It doesn't seem to support a filter according to the API docs. Please let me know if you have more details on this.

**Comment by thathaneydude** [comment]
In the UI, under "advanced" it gives you filtering options. If you watch the request you'll notice those filters being appended to the get params. For example: 

https://cloud.tenable.com/scans/27?filter.0.quality=eq&filter.0.filter=severity&filter.0.value=4&filter.search_type=and

That will filter scan 27 with only critical vulnerabilities. But you're correct, it doesn't look like that's been documented.
