### ISSUE TITLE
config.py error....

### ISSUE THREAD

**Issue by jbweiss** [tenable/Tenable.io-SDK-for-Python#49]
The file config.py contains a typo on line 4: AttributeError: 'module' object has no attribute 'PY34'

I believe the correct syntax is "six.PY3"

**Comment by alanfung** [comment]
@jbweiss `six.PY34` is specifically targeting for version 3.4. What version of six do you have installed? Unless it's removed in some newer version, it should be there in 1.10.0 <https://github.com/benjaminp/six/blob/1.10.0/six.py>.
