### ISSUE TITLE
agents and agent-groups should have scanner_id as variable. 

### ISSUE THREAD

**Issue by nkeuning** [tenable/Tenable.io-SDK-for-Python#61]
Scanner id should be a variable rather than hard coded to 1 for agent and agent-group api calls. 

GET /scanners/{scanner_id}/agents
line 30 and 40 in https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/api/agents.py

GET /scanners/{scanner_id}/agent-groups
line 17, 38, 51, 63/, 74 , 86, 107 and 118 in https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/api/agent_groups.py

**Comment by tenableAndrew** [comment]
Added in #72
