### ISSUE TITLE
Document order of authentication

### ISSUE THREAD

**Issue by paragbaxi** [tenable/Tenable.io-SDK-for-Python#7]
Hi can we document the precedence of authentication?

It appears from [https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/config.py](url) that the order is:
1. explicit in instantiation
2. environment variables
3. ini file

Is this correct?

**Comment by alanfung** [comment]
@paragbaxi ini file takes precedence over environment variables.

It's `constructor > ini file > environment variables`, I'll document this clearly in the README.

**Comment by alanfung** [comment]
@paragbaxi Update the README, let me know if it looks good to you.
