### ISSUE TITLE
Is NESSUS HOME version able to use SDK?

### ISSUE THREAD

**Issue by s032137** [tenable/Tenable.io-SDK-for-Python#77]
I am newbie in nessus home,I plan to use Tenable.io-SDK-for-Python to integrate into my PYTHON GUI.When I tested, it returned a 401 ERROR.Is NESSUS HOME version able to use SDK?

Thank you.

**Comment by mauvehed** [comment]
This SDK is for the tenable.io cloud product and does not cover Nessus to my knowledge. As well, Nessus version 7 recently removed the API from Nessus which would most certainly prevent this SDK or any other API framework from not functioning.

**Comment by tenableAndrew** [comment]
@mauvehed is correct, this SDK is only intended to be used with the [Tenable.io](https://www.tenable.com/products/tenable-io) platform.
