### ISSUE TITLE
Writing of File to Disk (tempfile)

### ISSUE THREAD

**Issue by skrtu** [tenable/Tenable.io-SDK-for-Python#97]
Could we change the writing of a file to disk to get the workbench data to something that writes to a file like object? With lowest privilege workstation accounts in a corporate environment I can't seem to make this work. 

```
with tempfile.NamedTemporaryFile() as temp:
            for chunk in iter_content:
                temp.write(chunk)
                temp.flush()
```

**Comment by tenableAndrew** [comment]
Where specifically were you hoping to see a change in the existing behavior? In https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/helpers/workbench.py#L65 and https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/helpers/workbench.py#L142 ?

**Comment by skrtu** [comment]
@tenableAndrew Yes thats correct.
