### ISSUE TITLE
Getting the state of a vulnerability from a ScanDetails

### ISSUE THREAD

**Issue by benlarsendk** [tenable/Tenable.io-SDK-for-Python#98]
I'm trying to get the state of a vulnerability, during a specific historic scan.
If I get my ScanDetails object as 

`scan_details = scan.details(history_instance.history_id)`

I'm not getting a list of model.Vulnerability back, but a list of dicts, which does not contain the state of the vulnerability, but only

- count
- severity
- plugin_family
- vuln_index
- plugin_name
- plugin_id

The only one missing is the state. 
Why is this? And is it possible to fix?

**Comment by tenableAndrew** [comment]
It doesn't look like the documented scan API currently supports returning the `vulnerability_state` details. This data is currently available from the `workbenches_api.vulnerabilities` or `workbenches_helper.vulnerabilities_api` methods, but that may not help you if you need to find the state for a specific historic scan, though most use cases seem to be focused on the current `vulnerability_state` not past states. 

I'll continue to look into this internally, the question here does not seem to be with the SDK, but rather with the data provided by the underlying public API the SDK is built on.

**Comment by benlarsendk** [comment]
Hi Andrew.
Thank you for the quick response. 
I agree with that the usecase probably is for the current state, though I can also see use cases for past states :) 
For the time being we'll use the CSV files to get that data. I hope it'll be a future feature in the API.

Have a good weekend.
