### ISSUE TITLE
If environment variables are not defined importing TenableIOClient will error

### ISSUE THREAD

**Issue by KoalaTea** [tenable/Tenable.io-SDK-for-Python#99]
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

This is due to a lack of defaults in some of the variables found in
tenable_io.config
specifically 

'access_key': environ.get('TENABLEIO_ACCESS_KEY'),
'secret_key': environ.get('TENABLEIO_SECRET_KEY'),
'http_proxy': environ.get('TENABLEIO_HTTP_PROXY'),
'https_proxy': environ.get('TENABLEIO_HTTPS_PROXY'),

**Comment by tenableAndrew** [comment]
Hi @KoalaTea, this appears to be a new issue when the SDK is used with Python 3.7.0, when those values are missing and python 3.5 or 3.6 are used it just results in a 401 being returned from any requests. We will work on a fix.
